# Form implementation generated from reading ui file 'giaodien.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 20, 681, 91))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 120, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 170, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lnehsa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnehsa.setGeometry(QtCore.QRect(270, 130, 113, 22))
        self.lnehsa.setObjectName("lnehsa")
        self.lnehsb = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnehsb.setGeometry(QtCore.QRect(270, 180, 113, 22))
        self.lnehsb.setObjectName("lnehsb")
        self.lnehsc = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnehsc.setGeometry(QtCore.QRect(270, 230, 113, 22))
        self.lnehsc.setObjectName("lnehsc")
        self.pushthoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushthoat.setGeometry(QtCore.QRect(680, 10, 93, 28))
        self.pushthoat.setObjectName("pushthoat")
        self.pushtinh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushtinh.setGeometry(QtCore.QRect(270, 280, 93, 28))
        self.pushtinh.setObjectName("pushtinh")
        self.lneinketqua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lneinketqua.setGeometry(QtCore.QRect(260, 340, 251, 41))
        self.lneinketqua.setObjectName("lneinketqua")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 340, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GIẢI PHƯƠNG TRÌNH BẬC 2"))
        self.label_2.setText(_translate("MainWindow", "Nhập hệ số a"))
        self.label_3.setText(_translate("MainWindow", "Nhập hệ số b"))
        self.label_4.setText(_translate("MainWindow", "Nhập hệ số c"))
        self.pushthoat.setText(_translate("MainWindow", "Thoát"))
        self.pushtinh.setText(_translate("MainWindow", "Tính"))
        self.label_5.setText(_translate("MainWindow", "Kết quả"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
