# Form implementation generated from reading ui file 'giaodien_text.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 701, 121))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lnetext = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnetext.setGeometry(QtCore.QRect(190, 140, 451, 51))
        self.lnetext.setObjectName("lnetext")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushnoi = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushnoi.setGeometry(QtCore.QRect(350, 220, 93, 28))
        self.pushnoi.setObjectName("pushnoi")
        self.pushquit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushquit.setGeometry(QtCore.QRect(350, 260, 93, 28))
        self.pushquit.setObjectName("pushquit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "NHẬP TEXT PHÁT RA ÂM THANH"))
        self.label_2.setText(_translate("MainWindow", "NHẬP TEXT MUỐN NÓI"))
        self.pushnoi.setText(_translate("MainWindow", "LÓI"))
        self.pushquit.setText(_translate("MainWindow", "THOÁT"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
