from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(911, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 20, 261, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lnetua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnetua.setGeometry(QtCore.QRect(170, 150, 71, 41))
        self.lnetua.setObjectName("lnetua")
        self.lnemaua = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnemaua.setGeometry(QtCore.QRect(170, 200, 71, 41))
        self.lnemaua.setObjectName("lnemaua")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(160, 186, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 170, 55, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 210, 61, 16))
        self.label_3.setObjectName("label_3")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(630, 176, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.lnetub = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnetub.setGeometry(QtCore.QRect(640, 140, 71, 41))
        self.lnetub.setObjectName("lnetub")
        self.lnemaub_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnemaub_2.setGeometry(QtCore.QRect(640, 190, 71, 41))
        self.lnemaub_2.setObjectName("lnemaub_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(540, 200, 61, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(550, 160, 55, 16))
        self.label_5.setObjectName("label_5")
        self.cong = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.cong.setGeometry(QtCore.QRect(330, 130, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cong.setFont(font)
        self.cong.setObjectName("cong")
        self.tru = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.tru.setGeometry(QtCore.QRect(330, 170, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tru.setFont(font)
        self.tru.setObjectName("tru")
        self.nhan = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.nhan.setGeometry(QtCore.QRect(330, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nhan.setFont(font)
        self.nhan.setObjectName("nhan")
        self.chia = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.chia.setGeometry(QtCore.QRect(330, 250, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chia.setFont(font)
        self.chia.setObjectName("chia")
        self.pushtinh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushtinh.setGeometry(QtCore.QRect(320, 300, 93, 28))
        self.pushtinh.setObjectName("pushtinh")
        self.lnekqtu = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lnekqtu.setGeometry(QtCore.QRect(320, 350, 91, 41))
        self.lnekqtu.setObjectName("lnekqtu")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(250, 360, 55, 16))
        self.label_6.setObjectName("label_6")
        self.pushthoat = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushthoat.setGeometry(QtCore.QRect(790, 10, 93, 28))
        self.pushthoat.setObjectName("pushthoat")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 911, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "PHÂN SỐ"))
        self.label_2.setText(_translate("MainWindow", "Nhập tử"))
        self.label_3.setText(_translate("MainWindow", "Nhập mẫu"))
        self.label_4.setText(_translate("MainWindow", "Nhập mẫu"))
        self.label_5.setText(_translate("MainWindow", "Nhập tử"))
        self.cong.setText(_translate("MainWindow", "CONG"))
        self.tru.setText(_translate("MainWindow", "TRU"))
        self.nhan.setText(_translate("MainWindow", "NHAN"))
        self.chia.setText(_translate("MainWindow", "CHIA"))
        self.pushtinh.setText(_translate("MainWindow", "TÍNH"))
        self.label_6.setText(_translate("MainWindow", "KẾT QUẢ"))
        self.pushthoat.setText(_translate("MainWindow", "thoát"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
